---
- name: copy current pacman.conf
  ansible.builtin.copy:
    src: /etc/pacman.conf
    dest: /etc/pacman.conf

- name: Run the equivalent of "pacman -Sy" as a separate step
  community.general.pacman:
    update_cache: yes

- name: base packages
  ansible.builtin.package:
    name:
      - acpi
      - tailscale
      - bolt
      - scrot
      - chromium
      - discord
      - xorg
      - libreoffice-still
      - hunspell
      - hunspell-en_us
      - hunspell-de
      - firefox
      - fwupd
      - glances
      - git
      - gtk2
      - lxappearance
      - neovim
      - numlockx
      - pass
      - pulsemixer
      - rsync
      - sshpass
      - sxhkd
      - sxiv
      - ttf-dejavu
      - ttf-liberation
      - udisks2
      - unclutter
      - wget
      - xclip
      - xdg-user-dirs
      - yubikey-manager
      - zathura
      - zsh
      - zsh-completions
    state: present

- name: WM tools
  ansible.builtin.package:
    name:
      - bspwm
      - dmenu
    state: present

- name: AMD graphics
  ansible.builtin.package:
    name:
      - xf86-video-amdgpu
      - radeontop
    state: present
  when: gpu == 'amd' or gpu == 'all'

- name: Intel graphics
  ansible.builtin.package:
    name:
      - xf86-video-intel
      - intel-gpu-tools
    state: present
  when: gpu == 'intel' or gpu == 'all'

- name: Nvidia graphics
  ansible.builtin.package:
    name:
      - xf86-video-nouveau
    state: present
  when: gpu == 'nvidia' or gpu == 'all'

- name: VM graphics
  ansible.builtin.package:
    name:
      - xf86-video-vesa
    state: present
  when: gpu == 'vm' or gpu == 'all'

- name: mesa
  ansible.builtin.package:
    name:
      - mesa
      - lib32-mesa
    state: present

- name: Enable bluetooth
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: yes
  become: yes
  loop:
    - libvirtd
    - tailscaled

