---
- name: copy current pacman.conf
  ansible.builtin.copy:
    src: /etc/pacman.conf
    dest: /etc/pacman.conf

- name: Run the equivalent of "pacman -Syu" as a separate step
  # Since community.general 5.0.0 the 'changed' state of this call
  # will be 'true' in case the cache was updated, or when a package
  # was updated.
  #
  # The previous behavior was to only indicate whether something was
  # upgraded. To keep the old behavior, add the following to the task:
  #
  #   register: result
  #   changed_when: result.packages | length > 0
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: base packages
  ansible.builtin.package:
    name:
        #- python-pdftotext
        #- unrar
        #- p7zip
        #- catdoc
        #- odt2txt
        #- docx2txt
        #- terraform
        #- terragrunt
      - acpi
      - aerc
      - alacritty
      - ansible
      - ansible-core
      - atool
      - aws-cli-v2
      - aws-vault
      - bolt
      - catimg
      - chromium
      - cifs-utils
      - discord
      - diskonaut
      - dnsutils
      - docker
      - docker-compose
      - dos2unix
      - dunst
      - element-desktop
      - fd
      - ffmpegthumbnailer
      - firefox
      - firefox-tridactyl
      - fprintd
      - fwupd
      - gimp
      - git
      - git
      - github-cli
      - glances
      - go-tools
      - gopls
      - gnome-themes-extra
      - gtk2
      - gtk-engine-murrine
      - helm
      - hunspell
      - hunspell-de
      - hunspell-en_us
      - jq
      - just
      - kubectl
      - lf
      - libreoffice-still
      - lnav
      - lxappearance
      - lynx
      - mariadb
      - mediainfo
      - molecule
      - neovim
      - nextcloud-client
      - nfs-utils
      - nmap
      - noto-fonts-cjk
      - ntfs-3g
      - numlockx
      - packer
      - pacman-contrib
      - pass
      - peco
      - pcmanfm
      - podman
      - podman-compose
      - polybar
      - pulsemixer
      - pulseaudio-bluetooth
      - pv
      - pyenv
      - pyright
        #- python-heatclient
      - python-openstack
      - python-pdftotext
      - python-pip
      - python-pipenv
      - python-poetry
      - qemu
      - rclone
      - restic
      - ripgrep-all
      - rsync
      - scrot
      - signal-desktop
      - smartmontools
      - snapper
      - snap-pac
      - sshpass
      - strace
      - sxhkd
      - sxiv
      - tailscale
      - tmux
      - transmission-cli
      - ttf-dejavu
      - ttf-liberation
      - udisks2
      - ueberzug
      - unclutter
      - vagrant
      - virt-install
      - virt-manager
      - w3m
      - wget
      - wol
      - xclip
      - xdg-user-dirs
      - xorg
      - yubikey-manager
      - zathura
      - zathura-pdf-mupdf
      - zsh
      - zsh-completions
    state: present

- name: WM tools
  ansible.builtin.package:
    name:
      - bspwm
      - dmenu
    state: present

- name: Enable services
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: yes
  become: yes
  loop:
    - tailscaled

- name: programming tools
  ansible.builtin.package:
    name:
      - bat
      - bash-language-server
      - shellcheck
    state: latest

- name: virtualization tools
  ansible.builtin.package:
    name:
      #- iptables-nft CONFLICT WITH IPTABLES
      - dnsmasq
      - virtualbox
        #- virtualbox-host-modules-arch ##TRY WITH VIRTUALBOX DISABLED
      - libvirt
      - virt-viewer
      - dmidecode
    state: latest
