---
- name: copy current pacman.conf
  ansible.builtin.copy:
    src: /etc/pacman.conf
    dest: /etc/pacman.conf

- name: Run the equivalent of "pacman -Sy" as a separate step
  community.general.pacman:
    update_cache: yes
    
- name: base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - bolt
    - xorg
    - libreoffice-still 
    - hunspell 
    - hunspell-en_us 
    - hunspell-de
    - firefox
    - fwupd
    - glances
    - gtk2
    - neovim
    - numlockx
    - pass
    - pulsemixer
    - rsync
    - sshpass
    - sxhkd
    - sxiv
    - ttf-dejavu
    - ttf-liberation
    - udisks2
    - unclutter
    - wget 
    - xclip
    - xdg-user-dirs
    - yubikey-manager
    - zathura
    - zsh
    - zsh-completions
 
- name: WM tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - bspwm
    - dmenu

- name: AMD graphics
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - xf86-video-amdgpu
    - radeontop
  tags:
    - amd

      #- name: Intel graphics
      #  ansible.builtin.package:
      #    name: "{{ item }}"
      #    state: present
      #  loop:
      #    - xf86-video-intel
      #    - intel-gpu-tools
      #  tags:
      #    - intel
      #
      #- name: Nvidia graphics
      #  ansible.builtin.package:
      #    name: "{{ item }}"
      #    state: present
      #  loop:
      #    - xf86-video-nouveau
      #  tags:
      #    - nvidia
      #
      #- name: VM graphics
      #  ansible.builtin.package:
      #    name: "{{ item }}"
      #    state: present
      #  loop:
      #    - xf86-video-vesa
      #  tags:
      #    - vm

- name: mesa
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - mesa
    - lib32-mesa
