---
- name: install some more packages
  community.general.pacman:
    name: '{{ item }}'
    state: present
    update_cache: true
  loop:
    - steam
    - lutris
  become: true

    #- name: steam btrfs subvolme
    #ansible.builtin.command: btrfs subvolume create '{{ home }}/.steam/steam/steamapps/common'
