---
- name: install some more packages
  community.general.pacman:
    name: '{{ item }}'
    state: present
    update_cache: true
  loop:
    - steam
    - lutris
  become: true

    #- name: steam btrfs subvolme
    #ansible.builtin.command: btrfs subvolume create '{{ home }}/.steam/steam/steamapps/common'

- name: AMD graphics
  ansible.builtin.package:
    name:
      - xf86-video-amdgpu
      - vulkan-radeon
      - lib32-vulkan-radeon
      - radeontop
    state: present
  become: true
  when: dgpu == 'amd' or dgpu == 'all'

    #- name: Intel graphics
    #  ansible.builtin.package:
    #    name:
    #      - xf86-video-intel
    #      - intel-gpu-tools
    #      - libva-utils
    #      - libva-intel-driver
    #    state: present
    #  when: dgpu == 'intel' or dgpu == 'all'
    #
    #- name: Nvidia graphics
    #  ansible.builtin.package:
    #    name:
    #      - xf86-video-nouveau
    #    state: present
    #  when: dgpu == 'nvidia' or dgpu == 'all'
    #
- name: VM graphics
  ansible.builtin.package:
    name:
      - xf86-video-vesa
    state: present
  become: true
  when: dgpu == 'vm' or dgpu == 'all'

- name: mesa
  ansible.builtin.package:
    name:
      - mesa
      - lib32-mesa
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - mesa-vdpau
      - lib32-mesa-vdpau
      - mesa-utils
    state: present
  become: true

