---
dependency:
  name: galaxy
  enabled: false
driver:
  name: vagrant
platforms:
  - name: archlinux
    box: archlinux/archlinux
    memory: 8192
      #    provider_raw_config_args:
      #      - "customize ['modifyvm', :id, '--nictype1', 'virtio']"
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
