#- name: include packages
#  ansible.builtin.import_tasks: packages.yml
#  become: yes
 
#- name: create some directories for later use
#  ansible.builtin.file:
#    path: '{{ home }}/{{ item }}'
#    state: directory
#  loop: 
#    - 'dev'
#    - '.local/share/nvim/site/autoload/'
#    - '.mozilla/firefox'
#    - '.config/systemd/user/'
#      #- '.steam/steam/steamapps'
#      
#- name: clone dotfiles with a separate git dir
#  ansible.builtin.git:
#    repo: 'git@github.com:ckstevenson/dotfiles.git'
#    accept_hostkey: yes # security risk
#    separate_git_dir: '{{ home }}/dev/dotfiles/'
#    dest: '{{ home }}/dotfiles-tmp'
#      #version: 'dev'
#      
#- name: synchronize passing in extra rsync options
#  ansible.posix.synchronize:
#    src: '{{ home }}/dotfiles-tmp/'
#    dest: '{{ home }}'
#    rsync_opts:
#      - "--exclude=.git"
#  delegate_to: "{{ inventory_hostname }}"
#
#- name: recursively remove directory
#  ansible.builtin.file:
#    path: '{{ home }}/dotfiles-tmp/'
#    state: absent

#- name: clone development repositories from github
#  ansible.builtin.git:
#    repo: '{{ item.repo }}'
#    accept_hostkey: yes # security risk
#    dest: '{{ item.dest }}'
#  loop: 
    #    - { dest: '{{ home }}/dev/archinstall', repo: 'git@github.com:ckstevenson/archinstall.git' }
    #    - { dest: '{{ home }}/dev/packer-templates-qemu', repo: 'git@github.com:ckstevenson/packer-templates-qemu.git' }
    #    - { dest: '{{ home }}/dev/tf-rancher', repo: 'git@github.com:ckstevenson/tf-rancher.git' }
    #    - { dest: '{{ home }}/dev/python-get-vm-info', repo: 'git@github.com:ckstevenson/python-get-vm-info.git' }
    #    - { dest: '{{ home }}/.local/bin/', repo: 'git@github.com:ckstevenson/scripts.git' }
    #    - { dest: '{{ home }}/dev/dmenu', repo: 'git@github.com:ckstevenson/dmenu.git' }
    #    - { dest: '{{ home }}/dev/paru', repo: 'https://aur.archlinux.org/paru.git' }
    #    - { dest: '{{ home }}/dev/st', repo: 'https://github.com/MrFinchMkV/st.git' }
    ###    - { dest: '{{ home }}/dev/nerd-fonts', repo: 'https://github.com/ryanoasis/nerd-fonts.git' }
    ####- { dest: '{{ home }}/dev/firefox-user.js', repo: 'https://github.com/pyllyukko/user.js/' }

- name: install vim plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ home }}/.local/share/nvim/site/autoload/plug.vim'

      #- name: pyright LSP
      #  ansible.builtin.pip:
      #    name: pyright

- name: create ssh-agent service
  ansible.builtin.copy:
    src: ssh-agent.service
    dest: '{{ home }}/.config/systemd/user/ssh-agent.service'

- name: enable ssh-agent service
  ansible.builtin.systemd:
    name: ssh-agent
    scope: user
    enabled: true

      #- name: Vagrant plugins
      #  ansible.builtin.shell: vagrant plugin install vagrant-libvirt

- name: git config
  ansible.builtin.shell: |
    git config --global user.name 'Cameron Stevenson'
    git config --global user.email 'cksteve@protonmail.com'

    #- name: nerd-fonts install
    #  ansible.builtin.shell: bash '{{ home }}/dev/nerd-fonts/install.sh'
