---
- name: Run the equivalent of "pacman -Syu" as a separate step
  # Since community.general 5.0.0 the 'changed' state of this call
  # will be 'true' in case the cache was updated, or when a package
  # was updated.
  #
  # The previous behavior was to only indicate whether something was
  # upgraded. To keep the old behavior, add the following to the task:
  #
  #   register: result
  #   changed_when: result.packages | length > 0
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: dev packages
  ansible.builtin.package:
    name:
      - ansible
      - mariadb
      - go-tools
      - aws-vault
      - podman
      - podman-compose
      - docker
      - docker-compose
      - fprintd
      - git 
      - github-cli
      - gopls
      - jq
      - just
      - kubectl
      - packer
      - pacman-contrib
      - pyenv
      - python-pip
      - python-pipenv
      - pyright
      - qemu
      #- terraform
      #- terragrunt
      - talos
      - cluster
      - davfs2
      - tmux
      - vagrant
      - virt-install
      - virt-manager
      - wol
    state: latest

- name: programming tools
  ansible.builtin.package:
    name:
      - bat
      - bash-language-server
      - shellcheck
    state: latest

- name: virtualization tools
  ansible.builtin.package:
    name:
      #- iptables-nft CONFLICT WITH IPTABLES
      - dnsmasq 
      - virtualbox
        #- virtualbox-host-modules-arch ##TRY WITH VIRTUALBOX DISABLED
      - libvirt
      - virt-viewer
      - dmidecode
    state: latest
