---
- name: dev packages
  ansible.builtin.package:
    name:
      - ansible
      - aws-vault
      - podman
      - podman-compose
      - docker
      - docker-compose
      - fprintd
      - git 
      - github-cli
      - gopls
      - jq
      - packer
      - pacman-contrib
      - pyenv
      - python-pip
      - python-pipenv
      - pyright
      - qemu
      - terraform
      - terragrunt
      - tmux
      - vagrant
      - virt-install
      - virt-manager
    state: latest

- name: programming tools
  ansible.builtin.package:
    name:
      - bat
      - bash-language-server
      - shellcheck
    state: latest

- name: virtualization tools
  ansible.builtin.package:
    name:
      #- iptables-nft CONFLICT WITH IPTABLES
      - dnsmasq 
      - virtualbox
        #- virtualbox-host-modules-arch ##TRY WITH VIRTUALBOX DISABLED
        #    - libvirt WAS ALREADY INSTALLED
      - virt-viewer
      - dmidecode
    state: latest
