# cd ./roles/{dev,base,laptop}/ && just

export VAGRANT_DEFAULT_PROVIDER := "libvirt"

test:
  cd {{invocation_directory()}} && \
  just molecule test

destroy: init
  cd {{invocation_directory()}} && \
  just molecule destroy

verify: init
  cd {{invocation_directory()}} &&  \
  just molecule verify

molecule sequence: init galaxy
  cd {{invocation_directory()}} && \
  poetry run molecule {{sequence}}

init:
  poetry install

galaxy:
  poetry run ansible-galaxy collection install -r ./requirements.yml

deploy: init
  poetry run ansible-playbook -kKi hosts.yml main.yml

ssh:
    vagrant ssh

# get the ip of running VMs
get-ip:
    virsh net-dhcp-leases --network vagrant-libvirt
