# Provisions Linux instances during the Packer deployment
---
- hosts: default
  vars:
    home: '/home/cameron'
  tasks:
    - name: Set authorized key for remote user copying it from current user
      ansible.posix.authorized_key:
        user: cameron
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    - name: Copy private key
      ansible.builtin.copy:
        src: '{{ home }}/.ssh/id_rsa'
        dest: '{{ home }}/.ssh/id_rsa'
        owner: cameron
        group: cameron
        mode: '0400'
    - name: Create XDG default dirs
      ansible.builtin.command: xdg-user-dirs-update
    - name: Create development directory    
      ansible.builtin.file:
        path: '{{ home }}/Dev'
        state: directory
    - name: Clone dotfiles with a separate Git dir
      ansible.builtin.git:
        repo: 'git@github.com:ckstevenson/dotfiles.git'
        accept_hostkey: yes # security risk
        separate_git_dir: '{{ home }}/Dev/dotfiles/'
        dest: '{{ home }}/dotfiles-tmp'
        version: 'dev'
    - name: Synchronize passing in extra rsync options
      ansible.posix.synchronize:
        src: '{{ home }}/dotfiles-tmp/'
        dest: '{{ home }}'
        rsync_opts:
          - "--exclude=.git"
      delegate_to: "{{ inventory_hostname }}"
    - name: Recursively remove directory
      ansible.builtin.file:
        path: '{{ home }}/dotfiles-tmp/'
        state: absent
    - name: Clone development repositories from GitHub
      ansible.builtin.git:
        repo: '{{ item.repo }}'
        accept_hostkey: yes # security risk
        dest: '{{ item.dest }}'
      loop: 
        - { dest: '{{ home }}/Dev/archinstall', repo: 'git@github.com:ckstevenson/archinstall.git' }
        - { dest: '{{ home }}/Dev/packer-templates-qemu', repo: 'git@github.com:ckstevenson/packer-templates-qemu.git' }
        - { dest: '{{ home }}/Dev/tf-rancher', repo: 'git@github.com:ckstevenson/tf-rancher.git' }
        - { dest: '{{ home }}/Dev/python-get-vm-info', repo: 'git@github.com:ckstevenson/python-get-vm-info.git' }
        - { dest: '{{ home }}/.local/bin/', repo: 'git@github.com:ckstevenson/scripts.git' }
        - { dest: '{{ home }}/Dev/paru', repo: 'git clone https://aur.archlinux.org/paru.git' }
        - { dest: '{{ home }}/Dev/st', repo: 'https://github.com/MentalOutlaw/st.git' }
    - name: Vim plug
      ansible.bultin.shell: |
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
