---
- hosts: localhost
  gather_facts: false
  vars:
    igpu: intel
    dgpu: amd
  roles:
    #- base
      #- laptop
    - gaming

# todo:
# * gpg keys
# * ssh key
# * tailscale induction
# * copy firefox configs
# * gnupass repository
# * st and dmenu install
# * vim plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && :PlugInstall
# * configure tlp (in-use) or laptop-mode-tools or acpid
# * HandleLidSwitch=suspend in /etc/systemd/logind.conf
# * implement gaming playbook features beyond gpu and cleanup igpu situation
# * 
