---
- hosts: localhost
  gather_facts: false
  vars:
    igpu: 'intel'
    dgpu: 'amd'
  roles:
    #- base
      #- laptop
    - gaming

# todo:
# * gpg keys
# * ssh key
# * tailscale induction
# * copy firefox configs
# * gnupass repository
# * st and dmenu install
# * paru makepkg -si
# * vim plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && :PlugInstall
# * configure powertop --auto-tune --auto-cpufreq (in-use), tlp or laptop-mode-tools or acpid
# * HandleLidSwitch=suspend in /etc/systemd/logind.conf
# * https://www.protondb.com/help/improving-performance
# * cleanup igpu driver choices
# * cleanup igpu placement
