---
- hosts: default
  gather_facts: false
  vars:
  roles:
    - base
    - dev
    - laptop
      #- gaming
          ####    - name: make zsh default shell
          ####      ansible.builtin.command: /usr/bin/chsh -s /usr/bin/zsh

       #### DON'T FORGET TO LINK user.js! ####
       # btrfs in archinstaller?
       # provisions linux instances during the packer deployment
       # enable libvirtd, dnsmasq iptables-nft
       # lutris
       # PV
       # enable docker and bluetooth
       # add disks_layout
       # link xorg.conf for desktop
       # mkdir ~/.cache/zsh/
       # touch ~/.cache/zsh/history
       # ssh keys from work
       # -a -G docker cameron
