---
- hosts: default
  gather_facts: false
  vars:
    igpu: intel
    dgpu: amd
  roles:
    - base
    - laptop
      #- gaming

# todo:
# * gpg keys
# * st and dmenu install
# * vim plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && :PlugInstall
# * configure tlp (in-use) or laptop-mode-tools or acpid
# * HandleLidSwitch=suspend in /etc/systemd/logind.conf

