# provisions linux instances during the packer deployment
---
- hosts: localhost
  vars:
    home: '/home/cameron'
  vars_files: './vault.yml'
  tasks:
    - name: gpg export
      ansible.builtin.command: |
        gpg --output './key.gpg' --passphrase '{{ gpg_pass }}' --export cksteve@protonmail.com
      delegate_to: localhost

    - name: copy the key
      ansible.builtin.copy:
        src: '.key.gpg'
        dest: '{{ home }}'

    - name: remove the key
      ansible.builtin.file:
        path: '.key.gpg'
        state: absent

    - name: gpg import
      ansible.builtin.command: |
        gpg --import '{{ home }}/key.gpg' --passphrase '{{ gpg_pass }}' 
