---
dependency:
  name: galaxy
  enabled: false
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: archlinux
    box: archlinux/archlinux
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
verifier:
  name: ansible
    #lint: |
    #  set -e
    #  yamllint .
    #  ansible-lint
    #  flake8
scenario:
  test_sequence:
    #- dependency
    #- lint
    #- cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    #- verify
    #- cleanup
    - destroy
